version: "3"
services:
  ###### DRUPAL 7 ######
  drupal:
    image: d7-custom:1.0
    container_name: drupal-7
    build: .
    restart: always
    environment:
      DATABASE_HOST: mysql
    ports:
      - 8080:80
    volumes:
      - files:/var/www/html
    networks:
      - network
    depends_on:
      - mysql

  ###### MySQL ######
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db_d7"
      MYSQL_USER: "usr_d7"
      MYSQL_PASSWORD: "d7"
      MYSQL_ROOT_PASSWORD: "d7"
      MYSQL_MAX_ALLOWED_PACKET: "1024M"
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - network

###### NETWORKS ######
networks:
  network:

###### VOLUMES ######
volumes:
  files:
  db:
