version: "3"
services:
  drupal:
    image: drupal:7.73
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./web/:/var/www/html/:rw,delegated
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_drupal'
      MYSQL_USER: 'usr_drupal'
      MYSQL_PASSWORD: 'drupal'
      MYSQL_MAX_ALLOWED_PACKET: '1024M'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
